import type { FormSchema } from 'hookra'

export const contactSchema: FormSchema = {
  title: 'Contact Us',
  description: 'Send us a message and we\'ll get back to you.',
  submitLabel: 'Send Message',
  layout: { columns: 2 },
  fields: [
    {
      name: 'firstName',
      type: 'text',
      label: 'First Name',
      required: true,
      placeholder: 'John',
    },
    {
      name: 'lastName',
      type: 'text',
      label: 'Last Name',
      required: true,
      placeholder: 'Doe',
    },
    {
      name: 'email',
      type: 'email',
      label: 'Email Address',
      required: 'We need your email to reply.',
      placeholder: 'john@example.com',
      width: 'full',
    },
    {
      name: 'subject',
      type: 'select',
      label: 'Subject',
      required: true,
      width: 'full',
      options: [
        { value: 'general', label: 'General Inquiry' },
        { value: 'support', label: 'Technical Support' },
        { value: 'billing', label: 'Billing Question' },
        { value: 'feedback', label: 'Feedback' },
        { value: 'partnership', label: 'Partnership' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      name: 'otherSubject',
      type: 'text',
      label: 'Please specify',
      required: true,
      width: 'full',
      dependsOn: { field: 'subject', value: 'other' },
    },
    {
      name: 'priority',
      type: 'radio',
      label: 'Priority',
      direction: 'row',
      defaultValue: 'normal',
      width: 'full',
      options: [
        { value: 'low', label: 'Low' },
        { value: 'normal', label: 'Normal' },
        { value: 'high', label: 'High' },
        { value: 'urgent', label: 'Urgent' },
      ],
    },
    {
      name: 'message',
      type: 'textarea',
      label: 'Message',
      required: 'Please enter your message.',
      placeholder: 'Describe your question or issue...',
      rows: 5,
      maxLength: 2000,
      showCount: true,
      width: 'full',
    },
    {
      name: 'attachment',
      type: 'file',
      label: 'Attachment (optional)',
      accept: 'image/*,.pdf,.doc,.docx',
      description: 'Images, PDFs, or Word documents',
      width: 'full',
    },
    {
      name: 'subscribe',
      type: 'boolean',
      label: 'Newsletter',
      checkboxLabel: 'Keep me updated with news and product updates',
      width: 'full',
    },
  ],
}
