import type { FormSchema } from 'formora'

export const enumObjectsSchema: FormSchema = {
  title: 'Enum & Option Patterns',
  description: 'Demonstrates various ways to use options: simple enums, disabled options, option descriptions, and dependent option sets.',
  showReset: true,
  sections: [
    {
      title: 'Basic Enum (Select)',
      columns: 2,
      fields: [
        {
          name: 'color',
          type: 'select',
          label: 'Favourite Colour',
          placeholder: 'Pick a colour...',
          options: [
            { value: 'red', label: 'Red' },
            { value: 'orange', label: 'Orange' },
            { value: 'yellow', label: 'Yellow' },
            { value: 'green', label: 'Green' },
            { value: 'blue', label: 'Blue' },
            { value: 'purple', label: 'Purple' },
          ],
        },
        {
          name: 'size',
          type: 'select',
          label: 'T-Shirt Size',
          options: [
            { value: 'xs', label: 'XS - Extra Small' },
            { value: 's', label: 'S - Small' },
            { value: 'm', label: 'M - Medium' },
            { value: 'l', label: 'L - Large' },
            { value: 'xl', label: 'XL - Extra Large' },
            { value: 'xxl', label: 'XXL - Double Extra Large' },
          ],
        },
      ],
    },
    {
      title: 'Disabled Options',
      description: 'Some options are disabled (greyed out, not selectable).',
      columns: 2,
      fields: [
        {
          name: 'plan',
          type: 'select',
          label: 'Subscription Plan',
          options: [
            { value: 'free', label: 'Free' },
            { value: 'starter', label: 'Starter — $9/mo' },
            { value: 'pro', label: 'Pro — $29/mo' },
            { value: 'enterprise', label: 'Enterprise — Contact us', disabled: true },
          ],
        },
        {
          name: 'shipping',
          type: 'radio',
          label: 'Shipping Method',
          options: [
            { value: 'standard', label: 'Standard (5-7 days)' },
            { value: 'express', label: 'Express (2-3 days)' },
            { value: 'overnight', label: 'Overnight (unavailable)', disabled: true },
          ],
        },
      ],
    },
    {
      title: 'Numeric & Boolean Option Values',
      description: 'Options can have number or boolean values, not just strings.',
      columns: 2,
      fields: [
        {
          name: 'rating',
          type: 'radio',
          label: 'Rating (Numeric Values)',
          direction: 'row',
          options: [
            { value: 1, label: '1 Star' },
            { value: 2, label: '2 Stars' },
            { value: 3, label: '3 Stars' },
            { value: 4, label: '4 Stars' },
            { value: 5, label: '5 Stars' },
          ],
        },
        {
          name: 'agree',
          type: 'radio',
          label: 'Agreement (Boolean Values)',
          direction: 'row',
          options: [
            { value: true, label: 'Yes, I agree' },
            { value: false, label: 'No, I disagree' },
          ],
        },
      ],
    },
    {
      title: 'Many Options',
      description: 'A select with many options — useful for country pickers, etc.',
      columns: 2,
      fields: [
        {
          name: 'country',
          type: 'select',
          label: 'Country',
          placeholder: 'Select your country...',
          options: [
            { value: 'af', label: 'Afghanistan' },
            { value: 'au', label: 'Australia' },
            { value: 'br', label: 'Brazil' },
            { value: 'ca', label: 'Canada' },
            { value: 'cn', label: 'China' },
            { value: 'dk', label: 'Denmark' },
            { value: 'eg', label: 'Egypt' },
            { value: 'fr', label: 'France' },
            { value: 'de', label: 'Germany' },
            { value: 'in', label: 'India' },
            { value: 'it', label: 'Italy' },
            { value: 'jp', label: 'Japan' },
            { value: 'mx', label: 'Mexico' },
            { value: 'ng', label: 'Nigeria' },
            { value: 'pk', label: 'Pakistan' },
            { value: 'ru', label: 'Russia' },
            { value: 'za', label: 'South Africa' },
            { value: 'kr', label: 'South Korea' },
            { value: 'es', label: 'Spain' },
            { value: 'se', label: 'Sweden' },
            { value: 'ch', label: 'Switzerland' },
            { value: 'uk', label: 'United Kingdom' },
            { value: 'us', label: 'United States' },
          ],
        },
        {
          name: 'language',
          type: 'select',
          label: 'Programming Language',
          placeholder: 'Select a language...',
          options: [
            { value: 'js', label: 'JavaScript' },
            { value: 'ts', label: 'TypeScript' },
            { value: 'py', label: 'Python' },
            { value: 'java', label: 'Java' },
            { value: 'go', label: 'Go' },
            { value: 'rust', label: 'Rust' },
            { value: 'cpp', label: 'C++' },
            { value: 'csharp', label: 'C#' },
            { value: 'ruby', label: 'Ruby' },
            { value: 'php', label: 'PHP' },
            { value: 'swift', label: 'Swift' },
            { value: 'kotlin', label: 'Kotlin' },
          ],
        },
      ],
    },
    {
      title: 'Checkbox Group with Many Options',
      fields: [
        {
          name: 'techStack',
          type: 'checkboxgroup',
          label: 'Tech Stack (select all that apply)',
          direction: 'row',
          options: [
            { value: 'react', label: 'React' },
            { value: 'vue', label: 'Vue' },
            { value: 'angular', label: 'Angular' },
            { value: 'svelte', label: 'Svelte' },
            { value: 'next', label: 'Next.js' },
            { value: 'nuxt', label: 'Nuxt' },
            { value: 'node', label: 'Node.js' },
            { value: 'deno', label: 'Deno' },
            { value: 'django', label: 'Django' },
            { value: 'rails', label: 'Rails' },
            { value: 'spring', label: 'Spring' },
            { value: 'dotnet', label: '.NET' },
          ],
        },
      ],
    },
  ],
}
