import type { FormSchema } from 'hookra'

export const largeFormSchema: FormSchema = {
  title: 'Employee Onboarding',
  description: 'A large, multi-section form demonstrating how the library handles complex real-world forms.',
  showReset: true,
  submitLabel: 'Complete Onboarding',
  sections: [
    {
      title: 'Personal Details',
      columns: 2,
      fields: [
        { name: 'firstName', type: 'text', label: 'First Name', required: true },
        { name: 'lastName', type: 'text', label: 'Last Name', required: true },
        { name: 'middleName', type: 'text', label: 'Middle Name' },
        { name: 'preferredName', type: 'text', label: 'Preferred Name' },
        { name: 'email', type: 'email', label: 'Personal Email', required: true },
        { name: 'phone', type: 'tel', label: 'Phone Number', required: true },
        { name: 'dateOfBirth', type: 'date', label: 'Date of Birth', required: true },
        {
          name: 'gender',
          type: 'select',
          label: 'Gender',
          options: [
            { value: 'male', label: 'Male' },
            { value: 'female', label: 'Female' },
            { value: 'nonbinary', label: 'Non-binary' },
            { value: 'prefer-not', label: 'Prefer not to say' },
          ],
        },
        {
          name: 'maritalStatus',
          type: 'select',
          label: 'Marital Status',
          options: [
            { value: 'single', label: 'Single' },
            { value: 'married', label: 'Married' },
            { value: 'divorced', label: 'Divorced' },
            { value: 'widowed', label: 'Widowed' },
          ],
        },
        {
          name: 'nationality',
          type: 'text',
          label: 'Nationality',
        },
      ],
    },
    {
      title: 'Address',
      collapsible: true,
      columns: 2,
      fields: [
        { name: 'address.line1', type: 'text', label: 'Address Line 1', required: true, width: 'full' },
        { name: 'address.line2', type: 'text', label: 'Address Line 2', width: 'full' },
        { name: 'address.city', type: 'text', label: 'City', required: true },
        { name: 'address.state', type: 'text', label: 'State / Province', required: true },
        { name: 'address.zip', type: 'text', label: 'ZIP / Postal Code', required: true },
        {
          name: 'address.country',
          type: 'select',
          label: 'Country',
          required: true,
          options: [
            { value: 'us', label: 'United States' },
            { value: 'uk', label: 'United Kingdom' },
            { value: 'ca', label: 'Canada' },
            { value: 'au', label: 'Australia' },
            { value: 'de', label: 'Germany' },
            { value: 'fr', label: 'France' },
            { value: 'jp', label: 'Japan' },
            { value: 'in', label: 'India' },
          ],
        },
      ],
    },
    {
      title: 'Employment Details',
      collapsible: true,
      columns: 2,
      fields: [
        {
          name: 'department',
          type: 'select',
          label: 'Department',
          required: true,
          options: [
            { value: 'engineering', label: 'Engineering' },
            { value: 'design', label: 'Design' },
            { value: 'product', label: 'Product' },
            { value: 'marketing', label: 'Marketing' },
            { value: 'sales', label: 'Sales' },
            { value: 'hr', label: 'Human Resources' },
            { value: 'finance', label: 'Finance' },
            { value: 'legal', label: 'Legal' },
            { value: 'operations', label: 'Operations' },
          ],
        },
        { name: 'jobTitle', type: 'text', label: 'Job Title', required: true },
        { name: 'startDate', type: 'date', label: 'Start Date', required: true },
        {
          name: 'employmentType',
          type: 'radio',
          label: 'Employment Type',
          direction: 'row',
          required: true,
          options: [
            { value: 'full-time', label: 'Full-time' },
            { value: 'part-time', label: 'Part-time' },
            { value: 'contract', label: 'Contract' },
            { value: 'intern', label: 'Intern' },
          ],
        },
        { name: 'manager', type: 'text', label: 'Reporting Manager' },
        { name: 'workEmail', type: 'email', label: 'Work Email' },
        {
          name: 'workLocation',
          type: 'radio',
          label: 'Work Location',
          direction: 'row',
          options: [
            { value: 'office', label: 'Office' },
            { value: 'remote', label: 'Remote' },
            { value: 'hybrid', label: 'Hybrid' },
          ],
        },
        {
          name: 'officeLocation',
          type: 'select',
          label: 'Office',
          dependsOn: {
            any: [
              { field: 'workLocation', value: 'office' },
              { field: 'workLocation', value: 'hybrid' },
            ],
          },
          options: [
            { value: 'sf', label: 'San Francisco' },
            { value: 'nyc', label: 'New York' },
            { value: 'london', label: 'London' },
            { value: 'berlin', label: 'Berlin' },
            { value: 'tokyo', label: 'Tokyo' },
          ],
        },
      ],
    },
    {
      title: 'Emergency Contact',
      collapsible: true,
      defaultCollapsed: true,
      columns: 2,
      fields: [
        { name: 'emergencyName', type: 'text', label: 'Contact Name', required: true },
        {
          name: 'emergencyRelation',
          type: 'select',
          label: 'Relationship',
          required: true,
          options: [
            { value: 'spouse', label: 'Spouse' },
            { value: 'parent', label: 'Parent' },
            { value: 'sibling', label: 'Sibling' },
            { value: 'friend', label: 'Friend' },
            { value: 'other', label: 'Other' },
          ],
        },
        { name: 'emergencyPhone', type: 'tel', label: 'Phone', required: true },
        { name: 'emergencyEmail', type: 'email', label: 'Email' },
      ],
    },
    {
      title: 'Skills & Interests',
      collapsible: true,
      defaultCollapsed: true,
      fields: [
        {
          name: 'skills',
          type: 'checkboxgroup',
          label: 'Technical Skills',
          direction: 'row',
          options: [
            { value: 'javascript', label: 'JavaScript' },
            { value: 'typescript', label: 'TypeScript' },
            { value: 'python', label: 'Python' },
            { value: 'java', label: 'Java' },
            { value: 'go', label: 'Go' },
            { value: 'rust', label: 'Rust' },
            { value: 'react', label: 'React' },
            { value: 'vue', label: 'Vue' },
            { value: 'angular', label: 'Angular' },
            { value: 'node', label: 'Node.js' },
            { value: 'docker', label: 'Docker' },
            { value: 'k8s', label: 'Kubernetes' },
          ],
        },
        {
          name: 'experience',
          type: 'slider',
          label: 'Years of Experience',
          min: 0,
          max: 30,
          step: 1,
          showValue: true,
          defaultValue: 5,
        },
        {
          name: 'bio',
          type: 'textarea',
          label: 'Short Bio',
          rows: 3,
          maxLength: 500,
          showCount: true,
          placeholder: 'Tell us about yourself, your background, and what you\'re excited about...',
        },
      ],
    },
    {
      title: 'IT Setup',
      collapsible: true,
      defaultCollapsed: true,
      columns: 2,
      fields: [
        {
          name: 'laptop',
          type: 'radio',
          label: 'Laptop Preference',
          direction: 'row',
          width: 'full',
          options: [
            { value: 'mac', label: 'MacBook Pro' },
            { value: 'windows', label: 'Windows Laptop' },
            { value: 'linux', label: 'Linux Laptop' },
          ],
        },
        {
          name: 'accessories',
          type: 'checkboxgroup',
          label: 'Additional Equipment',
          direction: 'row',
          width: 'full',
          options: [
            { value: 'monitor', label: 'External Monitor' },
            { value: 'keyboard', label: 'Mechanical Keyboard' },
            { value: 'mouse', label: 'External Mouse' },
            { value: 'headset', label: 'Headset' },
            { value: 'webcam', label: 'Webcam' },
            { value: 'standing-desk', label: 'Standing Desk' },
          ],
        },
        {
          name: 'softwareNeeds',
          type: 'textarea',
          label: 'Additional Software Needs',
          placeholder: 'List any specific software licenses you need...',
          rows: 2,
          width: 'full',
        },
      ],
    },
    {
      title: 'Agreements',
      fields: [
        {
          name: 'ndaSigned',
          type: 'checkbox',
          label: 'NDA',
          checkboxLabel: 'I have read and agree to the Non-Disclosure Agreement',
          required: 'NDA agreement is required',
        },
        {
          name: 'codeOfConduct',
          type: 'checkbox',
          label: 'Code of Conduct',
          checkboxLabel: 'I have read and agree to the Code of Conduct',
          required: 'Code of Conduct agreement is required',
        },
        {
          name: 'equipmentPolicy',
          type: 'checkbox',
          label: 'Equipment Policy',
          checkboxLabel: 'I acknowledge the company equipment usage policy',
          required: 'Equipment policy acknowledgement is required',
        },
      ],
    },
  ],
}
