import type { FormSchema } from 'hookra'

export const newChakraFieldsSchema: FormSchema = {
  title: 'New Chakra Form Components',
  description: 'Showcase of all newly added Chakra UI form components: PIN input, star rating, inline editable, segmented control, tags input, card selectors, Chakra Select, and the upgraded file upload with dropzone.',
  showReset: true,
  sections: [
    {
      title: 'PIN / OTP Input',
      description: 'Numeric or alphanumeric code entry using Chakra\'s PinInput component. Supports masking and OTP autocomplete.',
      columns: 2,
      fields: [
        {
          name: 'pin4',
          type: 'pin',
          label: '4-Digit PIN',
          length: 4,
          required: 'PIN is required',
          description: 'Enter your 4-digit PIN',
        },
        {
          name: 'otp6',
          type: 'pin',
          label: '6-Digit OTP',
          length: 6,
          otp: true,
          description: 'Enter the code from your authenticator app',
        },
        {
          name: 'pinMasked',
          type: 'pin',
          label: 'Masked PIN',
          length: 4,
          mask: true,
          description: 'Characters are hidden as you type',
        },
      ],
    },
    {
      title: 'Star Rating',
      description: 'Star-based rating input using Chakra\'s RatingGroup. Supports half stars and custom count.',
      columns: 2,
      fields: [
        {
          name: 'rating5',
          type: 'rating',
          label: 'Overall Rating',
          count: 5,
          defaultValue: 0,
          required: 'Please rate your experience',
        },
        {
          name: 'rating10',
          type: 'rating',
          label: 'Detailed Score (1–10)',
          count: 10,
          defaultValue: 7,
          description: 'Rate out of 10',
        },
        {
          name: 'ratingHalf',
          type: 'rating',
          label: 'Half-Star Rating',
          count: 5,
          allowHalf: true,
          defaultValue: 3.5,
          description: 'Supports 0.5 increments',
        },
      ],
    },
    {
      title: 'Inline Editable',
      description: 'Click-to-edit text using Chakra\'s Editable component — ideal for profile fields and settings that don\'t need a separate edit mode.',
      columns: 1,
      fields: [
        {
          name: 'editableName',
          type: 'editable',
          label: 'Display Name',
          defaultValue: 'John Doe',
          description: 'Click the pencil icon to edit',
          width: 'half',
        },
        {
          name: 'editableBio',
          type: 'editable',
          label: 'Bio',
          multiline: true,
          defaultValue: 'Full-stack developer with 5 years of experience building web apps.',
          description: 'Click the pencil icon to edit your bio',
          width: 'full',
        },
      ],
    },
    {
      title: 'Segmented Control',
      description: 'Pill-style segmented selector using Chakra\'s SegmentGroup — great for view mode switching and filters.',
      columns: 2,
      fields: [
        {
          name: 'viewMode',
          type: 'segmented',
          label: 'View Mode',
          defaultValue: 'grid',
          required: true,
          options: [
            { value: 'grid', label: 'Grid' },
            { value: 'list', label: 'List' },
            { value: 'table', label: 'Table' },
          ],
        },
        {
          name: 'timeRange',
          type: 'segmented',
          label: 'Time Range',
          defaultValue: '7d',
          options: [
            { value: '1d', label: '1D' },
            { value: '7d', label: '7D' },
            { value: '30d', label: '30D' },
            { value: '90d', label: '90D' },
            { value: 'all', label: 'All' },
          ],
        },
        {
          name: 'theme',
          type: 'segmented',
          label: 'Theme',
          defaultValue: 'system',
          options: [
            { value: 'light', label: 'Light' },
            { value: 'dark', label: 'Dark' },
            { value: 'system', label: 'System' },
          ],
        },
      ],
    },
    {
      title: 'Tags Input',
      description: 'Free-form tag entry using Chakra\'s TagsInput — press Enter to add a tag, click × to remove.',
      columns: 2,
      fields: [
        {
          name: 'skills',
          type: 'tags',
          label: 'Skills',
          placeholder: 'Add a skill…',
          max: 8,
          description: 'Press Enter to add (max 8)',
          defaultValue: ['React', 'TypeScript'],
        },
        {
          name: 'keywords',
          type: 'tags',
          label: 'SEO Keywords',
          placeholder: 'Add a keyword…',
          description: 'Press Enter to add tags',
        },
        {
          name: 'interests',
          type: 'tags',
          label: 'Interests',
          placeholder: 'Add an interest…',
          max: 5,
          allowDuplicates: false,
          description: 'Unique tags only (max 5)',
          defaultValue: ['Music', 'Travel'],
        },
      ],
    },
    {
      title: 'Radio Cards',
      description: 'Single-choice card selectors using Chakra\'s RadioCard — ideal for plan selection, type choosers, etc.',
      columns: 1,
      fields: [
        {
          name: 'plan',
          type: 'radiocard',
          label: 'Subscription Plan',
          required: 'Please select a plan',
          defaultValue: 'pro',
          options: [
            { value: 'free', label: 'Free', description: 'Up to 3 projects · 1 GB storage · Community support' },
            { value: 'pro', label: 'Pro', description: 'Unlimited projects · 100 GB storage · Priority email support' },
            { value: 'team', label: 'Team', description: 'Everything in Pro · Up to 25 seats · Shared workspaces' },
            { value: 'enterprise', label: 'Enterprise', description: 'Custom limits · SSO/SAML · Dedicated support SLA' },
          ],
          width: 'full',
        },
        {
          name: 'deployTarget',
          type: 'radiocard',
          label: 'Deploy Target',
          direction: 'row',
          defaultValue: 'cloud',
          options: [
            { value: 'cloud', label: 'Cloud', description: 'Managed hosting' },
            { value: 'edge', label: 'Edge', description: 'Global CDN' },
            { value: 'self', label: 'Self-hosted', description: 'Your own infra' },
          ],
          width: 'full',
        },
      ],
    },
    {
      title: 'Checkbox Cards',
      description: 'Multi-choice card selectors using Chakra\'s CheckboxCard — ideal for feature selection, permission toggles, etc.',
      columns: 1,
      fields: [
        {
          name: 'features',
          type: 'checkboxcard',
          label: 'Add-ons',
          defaultValue: ['analytics'],
          options: [
            { value: 'analytics', label: 'Analytics', description: 'Detailed usage reports and dashboards' },
            { value: 'audit_log', label: 'Audit Log', description: 'Full history of actions in your workspace' },
            { value: 'sso', label: 'SSO / SAML', description: 'Enterprise single sign-on integration' },
            { value: '2fa', label: '2FA Enforcement', description: 'Require two-factor auth for all members' },
          ],
          width: 'full',
        },
        {
          name: 'notifications',
          type: 'checkboxcard',
          label: 'Notification Channels',
          direction: 'row',
          defaultValue: ['email', 'push'],
          options: [
            { value: 'email', label: 'Email', description: 'Inbox alerts' },
            { value: 'push', label: 'Push', description: 'Browser & mobile' },
            { value: 'sms', label: 'SMS', description: 'Text messages' },
            { value: 'slack', label: 'Slack', description: 'Channel posts' },
          ],
          width: 'full',
        },
      ],
    },
    {
      title: 'Chakra Select (Rich Listbox)',
      description: 'Chakra\'s styled Select with a floating listbox — use variant: "chakra" for a more polished look than the native <select>.',
      columns: 2,
      fields: [
        {
          name: 'country',
          type: 'select',
          label: 'Country',
          variant: 'chakra',
          placeholder: 'Choose a country…',
          required: true,
          options: [
            { value: 'us', label: 'United States' },
            { value: 'gb', label: 'United Kingdom' },
            { value: 'de', label: 'Germany' },
            { value: 'fr', label: 'France' },
            { value: 'jp', label: 'Japan' },
            { value: 'au', label: 'Australia' },
            { value: 'ca', label: 'Canada' },
            { value: 'in', label: 'India' },
          ],
        },
        {
          name: 'timezone',
          type: 'select',
          label: 'Timezone',
          variant: 'chakra',
          placeholder: 'Select timezone…',
          defaultValue: 'utc',
          options: [
            { value: 'utc-12', label: 'UTC-12:00' },
            { value: 'utc-8', label: 'UTC-08:00 (Pacific)' },
            { value: 'utc-5', label: 'UTC-05:00 (Eastern)' },
            { value: 'utc', label: 'UTC+00:00 (London)' },
            { value: 'utc+1', label: 'UTC+01:00 (Paris)' },
            { value: 'utc+5.5', label: 'UTC+05:30 (Mumbai)' },
            { value: 'utc+8', label: 'UTC+08:00 (Singapore)' },
            { value: 'utc+9', label: 'UTC+09:00 (Tokyo)' },
          ],
        },
      ],
    },
    {
      title: 'File Upload with Dropzone',
      description: 'Chakra\'s FileUpload component with drag-and-drop dropzone, file previews, and per-file delete — replaces the plain <input type="file">.',
      columns: 1,
      fields: [
        {
          name: 'avatar',
          type: 'file',
          label: 'Profile Picture',
          accept: 'image/*',
          maxSize: 2097152,
          description: 'JPG, PNG or GIF · Max 2 MB',
          width: 'full',
        },
        {
          name: 'documents',
          type: 'file',
          label: 'Documents',
          accept: '.pdf,.doc,.docx',
          multiple: true,
          description: 'PDF or Word documents · Multiple files allowed',
          width: 'full',
        },
      ],
    },
  ],
}
