import type { FormSchema } from 'formora'

export const numbersSchema: FormSchema = {
  title: 'Numbers & Ranges',
  description: 'Demonstrates all numeric field types and their configuration options.',
  showReset: true,
  sections: [
    {
      title: 'Basic Numeric Inputs',
      columns: 2,
      fields: [
        {
          name: 'plainNumber',
          type: 'number',
          label: 'Plain Number',
          placeholder: 'Any number',
          description: 'No constraints — accepts any numeric value',
        },
        {
          name: 'integer',
          type: 'integer',
          label: 'Integer Only',
          placeholder: 'Whole numbers',
          description: 'Step is 1 by default',
        },
        {
          name: 'ranged',
          type: 'number',
          label: 'Ranged (0–100)',
          min: 0,
          max: 100,
          step: 5,
          description: 'min=0, max=100, step=5',
        },
        {
          name: 'decimal',
          type: 'number',
          label: 'Decimal Precision',
          min: 0,
          max: 10,
          step: 0.01,
          precision: 2,
          description: 'precision=2, step=0.01',
        },
        {
          name: 'clamped',
          type: 'number',
          label: 'Clamped on Blur',
          min: 1,
          max: 10,
          clampValueOnBlur: true,
          description: 'Type a value outside 1-10, then blur',
        },
        {
          name: 'negative',
          type: 'number',
          label: 'Allows Negative',
          min: -100,
          max: 100,
          step: 10,
          description: 'Range: -100 to 100',
        },
      ],
    },
    {
      title: 'Sliders',
      columns: 2,
      fields: [
        {
          name: 'basicSlider',
          type: 'slider',
          label: 'Basic Slider (0–100)',
          min: 0,
          max: 100,
          step: 1,
          showValue: true,
          defaultValue: 50,
          width: 'full',
        },
        {
          name: 'volumeSlider',
          type: 'slider',
          label: 'Volume',
          min: 0,
          max: 100,
          step: 5,
          showValue: true,
          defaultValue: 70,
          width: 'full',
        },
        {
          name: 'temperatureSlider',
          type: 'slider',
          label: 'Temperature (°C)',
          min: -20,
          max: 50,
          step: 1,
          showValue: true,
          defaultValue: 22,
          width: 'full',
        },
      ],
    },
    {
      title: 'With Validation',
      columns: 2,
      fields: [
        {
          name: 'validatedAge',
          type: 'integer',
          label: 'Age (13–120)',
          required: true,
          validation: {
            min: { value: 13, message: 'Must be at least 13 years old' },
            max: { value: 120, message: 'Please enter a realistic age' },
          },
        },
        {
          name: 'price',
          type: 'number',
          label: 'Price ($)',
          required: true,
          min: 0,
          step: 0.01,
          precision: 2,
          validation: {
            min: { value: 0.01, message: 'Price must be greater than zero' },
            max: { value: 99999, message: 'Price seems too high' },
          },
        },
        {
          name: 'quantity',
          type: 'integer',
          label: 'Quantity',
          required: true,
          min: 1,
          max: 999,
          defaultValue: 1,
          validation: {
            min: { value: 1, message: 'At least 1 item required' },
          },
        },
        {
          name: 'percentage',
          type: 'number',
          label: 'Percentage (%)',
          min: 0,
          max: 100,
          step: 0.1,
          validation: {
            min: { value: 0, message: 'Cannot be negative' },
            max: { value: 100, message: 'Cannot exceed 100%' },
          },
        },
      ],
    },
  ],
}
