import type { FormSchema } from 'formora'

export const registrationSchema: FormSchema = {
  title: 'Create Account',
  description: 'All fields marked with * are required.',
  showReset: true,
  layout: { columns: 2 },
  fields: [
    {
      name: 'firstName',
      type: 'text',
      label: 'First Name',
      placeholder: 'John',
      required: 'First name is required',
      width: 'half',
      validation: { minLength: 2, maxLength: 50 },
    },
    {
      name: 'lastName',
      type: 'text',
      label: 'Last Name',
      placeholder: 'Doe',
      required: true,
      width: 'half',
    },
    {
      name: 'email',
      type: 'email',
      label: 'Email Address',
      placeholder: 'john@example.com',
      required: true,
      width: 'full',
    },
    {
      name: 'password',
      type: 'password',
      label: 'Password',
      required: true,
      width: 'half',
      validation: {
        minLength: { value: 8, message: 'Password must be at least 8 characters' },
        pattern: {
          value: '(?=.*[A-Z])(?=.*[0-9])',
          message: 'Must contain at least one uppercase letter and one number',
        },
      },
    },
    {
      name: 'age',
      type: 'number',
      label: 'Age',
      placeholder: '18',
      width: 'half',
      validation: {
        min: { value: 13, message: 'You must be at least 13 years old' },
        max: 120,
      },
    },
    {
      name: 'country',
      type: 'select',
      label: 'Country',
      required: true,
      width: 'half',
      options: [
        { value: 'us', label: '🇺🇸 United States' },
        { value: 'uk', label: '🇬🇧 United Kingdom' },
        { value: 'ca', label: '🇨🇦 Canada' },
        { value: 'au', label: '🇦🇺 Australia' },
        { value: 'de', label: '🇩🇪 Germany' },
      ],
    },
    {
      name: 'state',
      type: 'text',
      label: 'State / Province',
      placeholder: 'California',
      width: 'half',
      description: 'Shown only for US / Canada',
      dependsOn: {
        any: [
          { field: 'country', value: 'us' },
          { field: 'country', value: 'ca' },
        ],
      },
    },
    {
      name: 'role',
      type: 'radio',
      label: 'Account Type',
      required: true,
      width: 'full',
      direction: 'row',
      options: [
        { value: 'developer', label: 'Developer' },
        { value: 'designer', label: 'Designer' },
        { value: 'manager', label: 'Manager' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      name: 'otherRole',
      type: 'text',
      label: 'Describe your role',
      required: true,
      width: 'full',
      dependsOn: { field: 'role', value: 'other' },
    },
    {
      name: 'interests',
      type: 'checkboxgroup',
      label: 'Interests',
      direction: 'row',
      width: 'full',
      options: [
        { value: 'web', label: 'Web Dev' },
        { value: 'mobile', label: 'Mobile' },
        { value: 'ai', label: 'AI / ML' },
        { value: 'devops', label: 'DevOps' },
        { value: 'security', label: 'Security' },
      ],
    },
    {
      name: 'bio',
      type: 'textarea',
      label: 'Short Bio',
      placeholder: 'Tell us about yourself…',
      width: 'full',
      rows: 3,
      maxLength: 300,
      showCount: true,
    },
    {
      name: 'newsletter',
      type: 'boolean',
      label: 'Subscribe to newsletter',
      checkboxLabel: 'Yes, send me updates and product news',
      width: 'full',
      defaultValue: true,
    },
    {
      name: 'agreeToTerms',
      type: 'checkbox',
      label: 'Terms & Conditions',
      checkboxLabel: 'I agree to the Terms of Service and Privacy Policy',
      required: 'You must accept the terms',
      width: 'full',
    },
  ],
}
