import type { FormSchema } from 'formora'

export const settingsSchema: FormSchema = {
  title: 'Application Settings',
  description: 'A settings/preferences page with toggles, selects, and conditional options.',
  submitLabel: 'Save Settings',
  showReset: true,
  sections: [
    {
      title: 'Display',
      columns: 2,
      fields: [
        {
          name: 'theme',
          type: 'radio',
          label: 'Theme',
          direction: 'row',
          defaultValue: 'system',
          options: [
            { value: 'light', label: 'Light' },
            { value: 'dark', label: 'Dark' },
            { value: 'system', label: 'System' },
          ],
          width: 'full',
        },
        {
          name: 'fontSize',
          type: 'slider',
          label: 'Font Size (px)',
          min: 12,
          max: 24,
          step: 1,
          showValue: true,
          defaultValue: 16,
        },
        {
          name: 'language',
          type: 'select',
          label: 'Language',
          defaultValue: 'en',
          options: [
            { value: 'en', label: 'English' },
            { value: 'es', label: 'Spanish' },
            { value: 'fr', label: 'French' },
            { value: 'de', label: 'German' },
            { value: 'ja', label: 'Japanese' },
            { value: 'zh', label: 'Chinese' },
          ],
        },
        {
          name: 'dateFormat',
          type: 'select',
          label: 'Date Format',
          defaultValue: 'mdy',
          options: [
            { value: 'mdy', label: 'MM/DD/YYYY' },
            { value: 'dmy', label: 'DD/MM/YYYY' },
            { value: 'ymd', label: 'YYYY-MM-DD' },
          ],
        },
        {
          name: 'timezone',
          type: 'select',
          label: 'Timezone',
          defaultValue: 'utc',
          options: [
            { value: 'utc', label: 'UTC' },
            { value: 'est', label: 'Eastern (EST)' },
            { value: 'cst', label: 'Central (CST)' },
            { value: 'mst', label: 'Mountain (MST)' },
            { value: 'pst', label: 'Pacific (PST)' },
          ],
        },
      ],
    },
    {
      title: 'Notifications',
      fields: [
        {
          name: 'emailNotifications',
          type: 'boolean',
          label: 'Email Notifications',
          checkboxLabel: 'Receive email notifications',
          defaultValue: true,
        },
        {
          name: 'emailFrequency',
          type: 'radio',
          label: 'Email Frequency',
          direction: 'row',
          defaultValue: 'daily',
          options: [
            { value: 'realtime', label: 'Real-time' },
            { value: 'daily', label: 'Daily Digest' },
            { value: 'weekly', label: 'Weekly Digest' },
          ],
          dependsOn: { field: 'emailNotifications', operator: 'truthy' },
        },
        {
          name: 'pushNotifications',
          type: 'boolean',
          label: 'Push Notifications',
          checkboxLabel: 'Enable browser push notifications',
          defaultValue: false,
        },
        {
          name: 'notifyTypes',
          type: 'checkboxgroup',
          label: 'Notify Me About',
          direction: 'row',
          options: [
            { value: 'mentions', label: 'Mentions' },
            { value: 'replies', label: 'Replies' },
            { value: 'updates', label: 'Product Updates' },
            { value: 'marketing', label: 'Marketing' },
          ],
        },
        {
          name: 'quietHoursEnabled',
          type: 'boolean',
          label: 'Quiet Hours',
          checkboxLabel: 'Enable quiet hours (no notifications during this time)',
        },
        {
          name: 'quietStart',
          type: 'time',
          label: 'Quiet Hours Start',
          defaultValue: '22:00',
          dependsOn: { field: 'quietHoursEnabled', operator: 'truthy' },
        },
        {
          name: 'quietEnd',
          type: 'time',
          label: 'Quiet Hours End',
          defaultValue: '08:00',
          dependsOn: { field: 'quietHoursEnabled', operator: 'truthy' },
        },
      ],
    },
    {
      title: 'Privacy & Security',
      fields: [
        {
          name: 'profileVisibility',
          type: 'radio',
          label: 'Profile Visibility',
          direction: 'row',
          defaultValue: 'public',
          options: [
            { value: 'public', label: 'Public' },
            { value: 'friends', label: 'Friends Only' },
            { value: 'private', label: 'Private' },
          ],
        },
        {
          name: 'twoFactorAuth',
          type: 'boolean',
          label: 'Two-Factor Authentication',
          checkboxLabel: 'Enable 2FA for my account',
        },
        {
          name: 'twoFactorMethod',
          type: 'radio',
          label: '2FA Method',
          direction: 'row',
          options: [
            { value: 'sms', label: 'SMS' },
            { value: 'authenticator', label: 'Authenticator App' },
            { value: 'email', label: 'Email' },
          ],
          dependsOn: { field: 'twoFactorAuth', operator: 'truthy' },
        },
        {
          name: 'sessionTimeout',
          type: 'select',
          label: 'Session Timeout',
          defaultValue: '30',
          options: [
            { value: '15', label: '15 minutes' },
            { value: '30', label: '30 minutes' },
            { value: '60', label: '1 hour' },
            { value: '120', label: '2 hours' },
            { value: 'never', label: 'Never' },
          ],
        },
      ],
    },
    {
      title: 'Data & Storage',
      collapsible: true,
      defaultCollapsed: true,
      fields: [
        {
          name: 'autoSave',
          type: 'boolean',
          label: 'Auto-Save',
          checkboxLabel: 'Automatically save drafts',
          defaultValue: true,
        },
        {
          name: 'autoSaveInterval',
          type: 'slider',
          label: 'Auto-Save Interval (seconds)',
          min: 5,
          max: 120,
          step: 5,
          showValue: true,
          defaultValue: 30,
          dependsOn: { field: 'autoSave', operator: 'truthy' },
        },
        {
          name: 'cacheEnabled',
          type: 'boolean',
          label: 'Cache',
          checkboxLabel: 'Enable local caching for faster loads',
          defaultValue: true,
        },
        {
          name: 'dataRetention',
          type: 'select',
          label: 'Data Retention',
          defaultValue: '90',
          options: [
            { value: '30', label: '30 days' },
            { value: '90', label: '90 days' },
            { value: '365', label: '1 year' },
            { value: 'forever', label: 'Forever' },
          ],
        },
      ],
    },
  ],
}
